import { Geist, Geist_Mono , Orbitron } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});     
const orbitron = Orbitron({
  variable: "--font-Orbitron-sans-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased h-full relative`}
      >
        {/* pointer-events-none যোগ করা হয়েছে যাতে এটি ক্লিক ব্লক না করে */}
        <div className="container h-full absolute left-1/2 top-0 -translate-x-1/2 line_left line_right pointer-events-none">
        </div>
        
        {/* মেনু বা নেভবার এখানে থাকবে */}
        {children}
      </body>
    </html>
  );
}
